// Auto-generated map: `${lessonId}/${stepId}` -> audio file under
// public/tutorial-audio/. Shared steps (boot, altsync, engage) reuse one clip.
// Steps with a `cues` array use per-cue keys `${lessonId}/${stepId}#${i}`.
// Voice: ElevenLabs "Kristen - Authoritative E-Learning Expert" (OIadkU6YLviNhuekXGly).
export const TUTORIAL_AUDIO = {
  // multi-task steps broken into one-instruction-at-a-time cues
  "startup/sel-alt#0": "startup-sel-alt-c0.mp3",
  "startup/sel-alt#1": "startup-sel-alt-c1.mp3",
  "startup/sel-alt#2": "startup-sel-alt-c2.mp3",
  "startup/sel-alt#3": "startup-sel-alt-c3.mp3",
  "startup/sel-alt#4": "startup-sel-alt-c4.mp3",
  "approach/platform#0": "approach-platform-c0.mp3",
  "approach/platform#1": "approach-platform-c1.mp3",
  "approach/platform#2": "approach-platform-c2.mp3",
  "approach/platform#3": "approach-platform-c3.mp3",
  "approach/platform#4": "approach-platform-c4.mp3",

  "emergencies/level-recover": "emergencies-level-recover.mp3",

  "startup/intro": "startup-intro.mp3",
  "startup/power-on": "startup-power-on.mp3",
  "startup/boot": "boot.mp3",
  "startup/altsync-open": "altsync-open.mp3",
  "startup/altsync-dial": "altsync-dial.mp3",
  "startup/engage": "engage.mp3",
  "startup/set-heading": "startup-set-heading.mp3",
  "startup/watch-turn": "startup-watch-turn.mp3",
  "startup/alt-hold": "startup-alt-hold.mp3",
  "startup/sel-alt": "startup-sel-alt.mp3",
  "startup/watch-capture": "startup-watch-capture.mp3",
  "startup/trim": "startup-trim.mp3",
  "startup/recap": "startup-recap.mp3",
  "approach/intro": "approach-intro.mp3",
  "approach/boot": "boot.mp3",
  "approach/src-430w": "approach-src-430w.mp3",
  "approach/altsync-open": "altsync-open.mp3",
  "approach/altsync-dial": "altsync-dial.mp3",
  "approach/start-iaf": "approach-start-iaf.mp3",
  "approach/engage": "engage.mp3",
  "approach/gpss": "approach-gpss.mp3",
  "approach/resync": "approach-resync.mp3",
  "approach/platform": "approach-platform.mp3",
  "approach/level-platform": "approach-level-platform.mp3",
  "approach/couple": "approach-couple.mp3",
  "approach/to-mins": "approach-to-mins.mp3",
  "approach/go-missed": "approach-go-missed.mp3",
  "approach/climb-out": "approach-climb-out.mp3",
  "approach/recap": "approach-recap.mp3",
  "skyview/intro": "skyview-intro.mp3",
  "skyview/boot": "boot.mp3",
  "skyview/src-skyview": "skyview-src-skyview.mp3",
  "skyview/altsync-open": "altsync-open.mp3",
  "skyview/altsync-dial": "altsync-dial.mp3",
  "skyview/hdg-bug": "skyview-hdg-bug.mp3",
  "skyview/alt-bug": "skyview-alt-bug.mp3",
  "skyview/vs-bug": "skyview-vs-bug.mp3",
  "skyview/enter-mode": "skyview-enter-mode.mp3",
  "skyview/althold": "skyview-althold.mp3",
  "skyview/cdi-gps": "skyview-cdi-gps.mp3",
  "skyview/ubaya": "skyview-ubaya.mp3",
  "skyview/watch-entry": "skyview-watch-entry.mp3",
  "skyview/stepdown": "skyview-stepdown.mp3",
  "skyview/watch-descent": "skyview-watch-descent.mp3",
  "skyview/crab": "skyview-crab.mp3",
  "skyview/exit-mode": "skyview-exit-mode.mp3",
  "skyview/recap": "skyview-recap.mp3",
  "emergencies/intro": "emergencies-intro.mp3",
  "emergencies/boot": "boot.mp3",
  "emergencies/induce-bank": "emergencies-induce-bank.mp3",
  "emergencies/level": "emergencies-level.mp3",
  "emergencies/level-revert": "emergencies-level-revert.mp3",
  "emergencies/min-as": "emergencies-min-as.mp3",
  "emergencies/cws": "emergencies-cws.mp3",
  "emergencies/disengage": "emergencies-disengage.mp3",
  "emergencies/aep-bank": "emergencies-aep-bank.mp3",
  "emergencies/aep-disable": "emergencies-aep-disable.mp3",
  "emergencies/sensor": "emergencies-sensor.mp3",
  "emergencies/power-cycle": "emergencies-power-cycle.mp3",
  "emergencies/gotcha": "emergencies-gotcha.mp3",
  "emergencies/recap": "emergencies-recap.mp3"
}
